// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SignOut</b><br>
 * Generated     : <b>2018/07/20 2:45:29 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  July 20, 2018
 * @author Jhansi.m
 */
public abstract class SignOutHelper extends RationalTestScript
{
	/**
	 * Home: with default state.
	 *		.id : Home
	 * 		.title : 
	 * 		.class : Html.SECTION
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_home() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_home"));
	}
	/**
	 * Home: with specific test context and state.
	 *		.id : Home
	 * 		.title : 
	 * 		.class : Html.SECTION
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_home(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_home"), anchor, flags);
	}
	
	/**
	 * userAccountMenu: with default state.
	 *		.id : userAccountMenu
	 * 		.title : 
	 * 		.class : Html.UL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userAccountMenu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userAccountMenu"));
	}
	/**
	 * userAccountMenu: with specific test context and state.
	 *		.id : userAccountMenu
	 * 		.title : 
	 * 		.class : Html.UL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userAccountMenu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userAccountMenu"), anchor, flags);
	}
	
	/**
	 * userAccountNav: with default state.
	 *		.id : userAccountNav
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userAccountNav() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userAccountNav"));
	}
	/**
	 * userAccountNav: with specific test context and state.
	 *		.id : userAccountNav
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userAccountNav(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userAccountNav"), anchor, flags);
	}
	
	/**
	 * global_signout: with default state.
	 *		.text : Sign out
	 * 		.id : global_signout
	 * 		.href : javascript:void(0);
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 12
	 */
	protected GuiTestObject link_global_signout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_global_signout"));
	}
	/**
	 * global_signout: with specific test context and state.
	 *		.text : Sign out
	 * 		.id : global_signout
	 * 		.href : javascript:void(0);
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 12
	 */
	protected GuiTestObject link_global_signout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_global_signout"), anchor, flags);
	}
	
	/**
	 * wilswilson004GmailCom: with default state.
	 *		.text :                                                                                  ...
	 * 		.id : userAccountLink
	 * 		.href : javascript:void(0);
	 * 		.title : wilswilson004@gmail.com
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 27
	 */
	protected GuiTestObject link_wilswilson004GmailCom() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_wilswilson004GmailCom"));
	}
	/**
	 * wilswilson004GmailCom: with specific test context and state.
	 *		.text :                                                                                  ...
	 * 		.id : userAccountLink
	 * 		.href : javascript:void(0);
	 * 		.title : wilswilson004@gmail.com
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 27
	 */
	protected GuiTestObject link_wilswilson004GmailCom(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_wilswilson004GmailCom"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point global_signout_text object in the SUT.
	 */
	protected IFtVerificationPoint global_signout_textVP() 
	{
		return vp("global_signout_text");
	}
	protected IFtVerificationPoint global_signout_textVP(TestObject anchor)
	{
		return vp("global_signout_text", anchor);
	}
	
	

	protected SignOutHelper()
	{
		setScriptName("SignOut");
	}
	
}

