// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.

import resources.SampleHelper;
import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;

// BEGIN custom imports 		
//TODO: Add custom imports here.
// END custom imports

/**
 * Description   : Functional Test Script
 * @author jhansi.m
 */
public class Sample extends SampleHelper
{
	/**
	 * Script Name   : <b>Sample</b>
	 * Generated     : <b>Feb 13, 2020 11:42:44 AM</b>
	 * Description   : Functional Test Script
	 * Original Host : WinNT Version 10.0  Build 15063 ()
	 * 
	 * @since  2020/02/13
	 * @author jhansi.m
	 */
	public void testMain(Object[] args) 
	{
		

		setSimplifiedScriptLine(1); //Start  Application  ClassicsJavaA  
		startApp("ClassicsJavaA");
							
		// Group: ClassicsCD
		setSimplifiedScriptLine(2); //ClassicsCD							
		timerStart("ClassicsCD_2");							
		setSimplifiedScriptLine(3); //Click  tree2  at  Composers->Schubert->Location(PLUS_MINUS)  
		tree2().click(atPath("Composers->Schubert->Location(PLUS_MINUS)"));
							
		setSimplifiedScriptLine(4); //Click  tree2  at  Composers->Schubert->String Quartets Nos. 4 & 14  
		tree2().click(atPath("Composers->Schubert->String Quartets Nos. 4 & 14"));
							
		setSimplifiedScriptLine(5); //Click  Place Order  
		placeOrder().click();
							
		timerStop("ClassicsCD_2");				
		// Group: Member Logon
		setSimplifiedScriptLine(6); //Member Logon							
		timerStart("MemberLogon_6");							
		setSimplifiedScriptLine(7); //Click  nameCombo  
		nameCombo().click();
							
		setSimplifiedScriptLine(8); //Click  nameCombo  at  Susan Flontly  
		nameCombo().click(atText("Susan Flontly"));
							
		setSimplifiedScriptLine(9); //Click  Password  
		password().click(atPoint(33,18));
							
		setSimplifiedScriptLine(10); //Type  Value  123
		memberLogon().inputKeys("{Num1}{Num2}{Num3}");
							
		setSimplifiedScriptLine(11); //Click  OK  
		ok().click();
							
		timerStop("MemberLogon_6");				
		// Group: Place an Order
		setSimplifiedScriptLine(12); //Place an Order							
		timerStart("PlaceanOrder_12");							
		setSimplifiedScriptLine(13); //Close  Place an Order  
		placeAnOrder().close();
							
		timerStop("PlaceanOrder_12");				
		// Group: ClassicsCD
		setSimplifiedScriptLine(14); //ClassicsCD							
		timerStart("ClassicsCD_14");							
		setSimplifiedScriptLine(15); //Close  ClassicsCD  
		classicsCD(ANY,MAY_EXIT).close();
							
		timerStop("ClassicsCD_14");				
	}
}
		