// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ButtonsInForm</b><br>
 * Generated     : <b>2020/05/12 7:27:01 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  May 12, 2020
 * @author Tester
 */
public abstract class ButtonsInFormHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Reset: with default state.
	 *		.id : 
	 * 		.type : reset
	 * 		.value : Reset
	 * 		.class : Html.INPUT.reset
	 * 		.title : 
	 * 		.name : Reset
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_reset() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reset"));
	}
	/**
	 * Reset: with specific test context and state.
	 *		.id : 
	 * 		.type : reset
	 * 		.value : Reset
	 * 		.class : Html.INPUT.reset
	 * 		.title : 
	 * 		.name : Reset
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_reset(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reset"), anchor, flags);
	}
	
	/**
	 * YesIWantToRegisterToWinTheComputerChairsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Yes, I want to register to win the computer chair
	 * 		.class : Html.INPUT.submit
	 * 		.title : 
	 * 		.name : submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesIWantToRegisterToWin() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesIWantToRegisterToWin"));
	}
	/**
	 * YesIWantToRegisterToWinTheComputerChairsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Yes, I want to register to win the computer chair
	 * 		.class : Html.INPUT.submit
	 * 		.title : 
	 * 		.name : submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesIWantToRegisterToWin(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesIWantToRegisterToWin"), anchor, flags);
	}
	
	/**
	 * ContestPage: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Contest page
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"));
	}
	/**
	 * ContestPage: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Contest page
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"), anchor, flags);
	}
	
	

	protected ButtonsInFormHelper()
	{
		setScriptName("ButtonsInForm");
	}
	
}

