// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>FTAriesWeb</b><br>
 * Generated     : <b>2020/04/04 8:42:51 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  April 04, 2020
 * @author vatsalas
 */
public abstract class FTAriesWebHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * AriesWebContestPageIframe: with default state.
	 *		.title : Aries-web contest page - Iframe
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/aries-webContestPageiframe. ...
	 */
	protected DocumentTestObject document_ariesWebContestPageIf() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ariesWebContestPageIf"));
	}
	/**
	 * AriesWebContestPageIframe: with specific test context and state.
	 *		.title : Aries-web contest page - Iframe
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/aries-webContestPageiframe. ...
	 */
	protected DocumentTestObject document_ariesWebContestPageIf(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ariesWebContestPageIf"), anchor, flags);
	}
	
	/**
	 * position: with default state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"));
	}
	/**
	 * position: with specific test context and state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"), anchor, flags);
	}
	
	/**
	 * salary: with default state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"));
	}
	/**
	 * salary: with specific test context and state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * address: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"));
	}
	/**
	 * address: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"), anchor, flags);
	}
	
	/**
	 * buyerDescription: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"));
	}
	/**
	 * buyerDescription: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"), anchor, flags);
	}
	
	/**
	 * City: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"));
	}
	/**
	 * City: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"), anchor, flags);
	}
	
	/**
	 * email: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"));
	}
	/**
	 * email: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"), anchor, flags);
	}
	
	/**
	 * Name: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"));
	}
	/**
	 * Name: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"), anchor, flags);
	}
	
	/**
	 * State: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"));
	}
	/**
	 * State: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"), anchor, flags);
	}
	
	/**
	 * Zip: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"));
	}
	/**
	 * Zip: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"), anchor, flags);
	}
	
	

	protected FTAriesWebHelper()
	{
		setScriptName("FTAriesWeb");
	}
	
}

