// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>html_8604_Frames5</b><br>
 * Generated     : <b>2019/02/12 12:59:38 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  February 12, 2019
 * @author JaspreetSinghC
 */
public abstract class html_8604_Frames5Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * backButton: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : back-button
	 */
	protected GuiTestObject button_backButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_backButton"));
	}
	/**
	 * backButton: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : back-button
	 */
	protected GuiTestObject button_backButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_backButton"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel :     
	 * 		accessibleContext.accessibleName : Close
	 * 		.classIndex : 2
	 */
	protected GuiTestObject close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel :     
	 * 		accessibleContext.accessibleName : Close
	 * 		.classIndex : 2
	 */
	protected GuiTestObject close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"), anchor, flags);
	}
	
	/**
	 * ALTTextTestPage: with default state.
	 *		.title : ALT Text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/alt.htm
	 */
	protected DocumentTestObject document_altTextTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_altTextTestPage"));
	}
	/**
	 * ALTTextTestPage: with specific test context and state.
	 *		.title : ALT Text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/alt.htm
	 */
	protected DocumentTestObject document_altTextTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_altTextTestPage"), anchor, flags);
	}
	
	/**
	 * FrameExamplePage: with default state.
	 *		.title : Frame Example Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/frametest/index.html
	 */
	protected DocumentTestObject document_frameExamplePage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_frameExamplePage"));
	}
	/**
	 * FrameExamplePage: with specific test context and state.
	 *		.title : Frame Example Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/frametest/index.html
	 */
	protected DocumentTestObject document_frameExamplePage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_frameExamplePage"), anchor, flags);
	}
	
	/**
	 * HREFIMGTestPage: with default state.
	 *		.title : HREF, IMG Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 */
	protected DocumentTestObject document_hrefimgTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_hrefimgTestPage"));
	}
	/**
	 * HREFIMGTestPage: with specific test context and state.
	 *		.title : HREF, IMG Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 */
	protected DocumentTestObject document_hrefimgTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_hrefimgTestPage"), anchor, flags);
	}
	
	/**
	 * IDTestPage: with default state.
	 *		.title : ID Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/id.htm
	 */
	protected DocumentTestObject document_idTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_idTestPage"));
	}
	/**
	 * IDTestPage: with specific test context and state.
	 *		.title : ID Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/id.htm
	 */
	protected DocumentTestObject document_idTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_idTestPage"), anchor, flags);
	}
	
	/**
	 * LinkTestPage: with default state.
	 *		.title : Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/link.htm
	 */
	protected DocumentTestObject document_linkTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_linkTestPage"));
	}
	/**
	 * LinkTestPage: with specific test context and state.
	 *		.title : Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/link.htm
	 */
	protected DocumentTestObject document_linkTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_linkTestPage"), anchor, flags);
	}
	
	/**
	 * LinkTestPage: with default state.
	 *		.title : Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/index.htm
	 */
	protected DocumentTestObject document_linkTestPage2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_linkTestPage2"));
	}
	/**
	 * LinkTestPage: with specific test context and state.
	 *		.title : Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/index.htm
	 */
	protected DocumentTestObject document_linkTestPage2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_linkTestPage2"), anchor, flags);
	}
	
	/**
	 * LongLinkTestPage: with default state.
	 *		.title : Long Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink.htm
	 */
	protected DocumentTestObject document_longLinkTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_longLinkTestPage"));
	}
	/**
	 * LongLinkTestPage: with specific test context and state.
	 *		.title : Long Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink.htm
	 */
	protected DocumentTestObject document_longLinkTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_longLinkTestPage"), anchor, flags);
	}
	
	/**
	 * NameIDAndAltTextTestPage: with default state.
	 *		.title : Name, ID and Alt text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameidalt.htm
	 */
	protected DocumentTestObject document_nameIDAndAltTextTestP() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameIDAndAltTextTestP"));
	}
	/**
	 * NameIDAndAltTextTestPage: with specific test context and state.
	 *		.title : Name, ID and Alt text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameidalt.htm
	 */
	protected DocumentTestObject document_nameIDAndAltTextTestP(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameIDAndAltTextTestP"), anchor, flags);
	}
	
	/**
	 * NameIDTestPage: with default state.
	 *		.title : Name & ID Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameid.htm
	 */
	protected DocumentTestObject document_nameIDTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameIDTestPage"));
	}
	/**
	 * NameIDTestPage: with specific test context and state.
	 *		.title : Name & ID Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameid.htm
	 */
	protected DocumentTestObject document_nameIDTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameIDTestPage"), anchor, flags);
	}
	
	/**
	 * NameTestPage: with default state.
	 *		.title : Name Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/name.htm
	 */
	protected DocumentTestObject document_nameTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameTestPage"));
	}
	/**
	 * NameTestPage: with specific test context and state.
	 *		.title : Name Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/name.htm
	 */
	protected DocumentTestObject document_nameTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_nameTestPage"), anchor, flags);
	}
	
	/**
	 * NoALTTextTestPage: with default state.
	 *		.title : No ALT Text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/noalt.htm
	 */
	protected DocumentTestObject document_noALTTextTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_noALTTextTestPage"));
	}
	/**
	 * NoALTTextTestPage: with specific test context and state.
	 *		.title : No ALT Text Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/noalt.htm
	 */
	protected DocumentTestObject document_noALTTextTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_noALTTextTestPage"), anchor, flags);
	}
	
	/**
	 * TheOTHERLongLinkTestPage: with default state.
	 *		.title : The OTHER Long Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink2.htm
	 */
	protected DocumentTestObject document_theOTHERLongLinkTestP() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theOTHERLongLinkTestP"));
	}
	/**
	 * TheOTHERLongLinkTestPage: with specific test context and state.
	 *		.title : The OTHER Long Link Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink2.htm
	 */
	protected DocumentTestObject document_theOTHERLongLinkTestP(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_theOTHERLongLinkTestP"), anchor, flags);
	}
	
	/**
	 * TitleTestPage: with default state.
	 *		.title : Title Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/title.htm
	 */
	protected DocumentTestObject document_titleTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_titleTestPage"));
	}
	/**
	 * TitleTestPage: with specific test context and state.
	 *		.title : Title Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/title.htm
	 */
	protected DocumentTestObject document_titleTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_titleTestPage"), anchor, flags);
	}
	
	/**
	 * HtmlFRAME: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FRAME
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected StatelessGuiSubitemTestObject frame_htmlFRAME() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("frame_htmlFRAME"));
	}
	/**
	 * HtmlFRAME: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FRAME
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected StatelessGuiSubitemTestObject frame_htmlFRAME(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("frame_htmlFRAME"), anchor, flags);
	}
	
	/**
	 * AreYouHungryIAm: with default state.
	 *		.alt : Are you hungry?, I am!
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hamburger.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_areYouHungryIAm() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_areYouHungryIAm"));
	}
	/**
	 * AreYouHungryIAm: with specific test context and state.
	 *		.alt : Are you hungry?, I am!
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hamburger.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_areYouHungryIAm(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_areYouHungryIAm"), anchor, flags);
	}
	
	/**
	 * hamburger: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hamburger.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_hamburger() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_hamburger"));
	}
	/**
	 * hamburger: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hamburger.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_hamburger(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_hamburger"), anchor, flags);
	}
	
	/**
	 * offer: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/offer.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_offer() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_offer"));
	}
	/**
	 * offer: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/offer.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_offer(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_offer"), anchor, flags);
	}
	
	/**
	 * offer: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/offer.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_offer2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_offer2"));
	}
	/**
	 * offer: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/offer.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_offer2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_offer2"), anchor, flags);
	}
	
	/**
	 * regionalGardeningMap: with default state.
	 *		.alt : regional gardening map
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/imagemap/garden ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_regionalGardeningMap() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_regionalGardeningMap"));
	}
	/**
	 * regionalGardeningMap: with specific test context and state.
	 *		.alt : regional gardening map
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/imagemap/garden ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_regionalGardeningMap(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_regionalGardeningMap"), anchor, flags);
	}
	
	/**
	 * _99: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 99
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/id.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__99() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__99"));
	}
	/**
	 * _99: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 99
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/id.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__99(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__99"), anchor, flags);
	}
	
	/**
	 * _LinkTestForHTMLExtension_: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/alt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link__LinkTestForHTMLExtension() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__LinkTestForHTMLExtension"));
	}
	/**
	 * _LinkTestForHTMLExtension_: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/alt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link__LinkTestForHTMLExtension(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__LinkTestForHTMLExtension"), anchor, flags);
	}
	
	/**
	 * _LinkTestForHTMLExtension_: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/noalt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link__LinkTestForHTMLExtension2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__LinkTestForHTMLExtension2"));
	}
	/**
	 * _LinkTestForHTMLExtension_: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/noalt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link__LinkTestForHTMLExtension2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__LinkTestForHTMLExtension2"), anchor, flags);
	}
	
	/**
	 * _WhatSMyCarWorth: with default state.
	 *		.text :  What's My Car Worth?
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__WhatSMyCarWorth() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__WhatSMyCarWorth"));
	}
	/**
	 * _WhatSMyCarWorth: with specific test context and state.
	 *		.text :  What's My Car Worth?
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__WhatSMyCarWorth(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__WhatSMyCarWorth"), anchor, flags);
	}
	
	/**
	 * LinkTestPage: with default state.
	 *		.text : Link test page
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/index.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_linkTestPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_linkTestPage"));
	}
	/**
	 * LinkTestPage: with specific test context and state.
	 *		.text : Link test page
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/index.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_linkTestPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_linkTestPage"), anchor, flags);
	}
	
	/**
	 * LongLinkTestTHisIsTheLongLinkTestThisTextJustGoes: with default state.
	 *		.text : Long link test. THis is the long link test, this text just goes on and on and on ...
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link_longLinkTestTHisIsTheLong() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_longLinkTestTHisIsTheLong"));
	}
	/**
	 * LongLinkTestTHisIsTheLongLinkTestThisTextJustGoes: with specific test context and state.
	 *		.text : Long link test. THis is the long link test, this text just goes on and on and on ...
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected GuiTestObject link_longLinkTestTHisIsTheLong(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_longLinkTestTHisIsTheLong"), anchor, flags);
	}
	
	/**
	 * LongLinkTestTHisIsTheLongLinkTestThisTextJustGoes: with default state.
	 *		.text : Long link test. THis is the long link test, this text just goes on and on and on ...
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink2.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	protected GuiTestObject link_longLinkTestTHisIsTheLong2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_longLinkTestTHisIsTheLong2"));
	}
	/**
	 * LongLinkTestTHisIsTheLongLinkTestThisTextJustGoes: with specific test context and state.
	 *		.text : Long link test. THis is the long link test, this text just goes on and on and on ...
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/longlink2.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 9
	 */
	protected GuiTestObject link_longLinkTestTHisIsTheLong2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_longLinkTestTHisIsTheLong2"), anchor, flags);
	}
	
	/**
	 * nametest: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/name.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_nametest() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest"));
	}
	/**
	 * nametest: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/name.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_nametest(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest"), anchor, flags);
	}
	
	/**
	 * nametest2: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 98
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameid.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest2
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_nametest2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest2"));
	}
	/**
	 * nametest2: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 98
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameid.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest2
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_nametest2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest2"), anchor, flags);
	}
	
	/**
	 * nametest3: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 97
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameidalt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest3
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link_nametest3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest3"));
	}
	/**
	 * nametest3: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 97
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/nameidalt.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : nametest3
	 * 		.classIndex : 5
	 */
	protected GuiTestObject link_nametest3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nametest3"), anchor, flags);
	}
	
	/**
	 * TextTaggedAsLinkTest: with default state.
	 *		.text :  link!
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/link.htm
	 * 		.title : Text tagged as link test!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link_textTaggedAsLinkTest() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_textTaggedAsLinkTest"));
	}
	/**
	 * TextTaggedAsLinkTest: with specific test context and state.
	 *		.text :  link!
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/link.htm
	 * 		.title : Text tagged as link test!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link_textTaggedAsLinkTest(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_textTaggedAsLinkTest"), anchor, flags);
	}
	
	/**
	 * ThisIsTheTitleText: with default state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/title.htm
	 * 		.title : This is the Title text
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link_thisIsTheTitleText() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_thisIsTheTitleText"));
	}
	/**
	 * ThisIsTheTitleText: with specific test context and state.
	 *		.text : _Link test for HTML extension_
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/title.htm
	 * 		.title : This is the Title text
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 6
	 */
	protected GuiTestObject link_thisIsTheTitleText(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_thisIsTheTitleText"), anchor, flags);
	}
	
	/**
	 * WhatSMyCarWorthIsItWorthSellingFindOutHere: with default state.
	 *		.text : What's My Car Worth?Is it worth selling? Find out here! 
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_whatSMyCarWorthIsItWorthS() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_whatSMyCarWorthIsItWorthS"));
	}
	/**
	 * WhatSMyCarWorthIsItWorthSellingFindOutHere: with specific test context and state.
	 *		.text : What's My Car Worth?Is it worth selling? Find out here! 
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/link_tests/hrefimg.htm
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_whatSMyCarWorthIsItWorthS(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_whatSMyCarWorthIsItWorthS"), anchor, flags);
	}
	
	/**
	 * FrameExamplePage: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Frame Example Page
	 */
	protected BrowserTabTestObject pageTab_frameExamplePage() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_frameExamplePage"));
	}
	/**
	 * FrameExamplePage: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Frame Example Page
	 */
	protected BrowserTabTestObject pageTab_frameExamplePage(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_frameExamplePage"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"));
	}
	/**
	 * HtmlTable_1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point ALTTextTestPage_ALTTextTestPage object in the SUT.
	 */
	protected IFtVerificationPoint ALTTextTestPage_ALTTextTestPageVP() 
	{
		return vp("ALTTextTestPage_ALTTextTestPage");
	}
	protected IFtVerificationPoint ALTTextTestPage_ALTTextTestPageVP(TestObject anchor)
	{
		return vp("ALTTextTestPage_ALTTextTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point AreYouHungryIAm_AreYouHungryIAm object in the SUT.
	 */
	protected IFtVerificationPoint AreYouHungryIAm_AreYouHungryIAmVP() 
	{
		return vp("AreYouHungryIAm_AreYouHungryIAm");
	}
	protected IFtVerificationPoint AreYouHungryIAm_AreYouHungryIAmVP(TestObject anchor)
	{
		return vp("AreYouHungryIAm_AreYouHungryIAm", anchor);
	}
	
	/**
	 * Locate and return the verification point hamburger_hamburger object in the SUT.
	 */
	protected IFtVerificationPoint hamburger_hamburgerVP() 
	{
		return vp("hamburger_hamburger");
	}
	protected IFtVerificationPoint hamburger_hamburgerVP(TestObject anchor)
	{
		return vp("hamburger_hamburger", anchor);
	}
	
	/**
	 * Locate and return the verification point HREFIMGTestPage_HREFIMGTestPage object in the SUT.
	 */
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPageVP() 
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage");
	}
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPageVP(TestObject anchor)
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point HREFIMGTestPage_HREFIMGTestPage_2 object in the SUT.
	 */
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPage_2VP() 
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage_2");
	}
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPage_2VP(TestObject anchor)
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage_2", anchor);
	}
	
	/**
	 * Locate and return the verification point HREFIMGTestPage_HREFIMGTestPage_3 object in the SUT.
	 */
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPage_3VP() 
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage_3");
	}
	protected IFtVerificationPoint HREFIMGTestPage_HREFIMGTestPage_3VP(TestObject anchor)
	{
		return vp("HREFIMGTestPage_HREFIMGTestPage_3", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_gridVP() 
	{
		return vp("HtmlTable_0_grid");
	}
	protected IFtVerificationPoint HtmlTable_0_gridVP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_1_grid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_1_gridVP() 
	{
		return vp("HtmlTable_1_grid");
	}
	protected IFtVerificationPoint HtmlTable_1_gridVP(TestObject anchor)
	{
		return vp("HtmlTable_1_grid", anchor);
	}
	
	/**
	 * Locate and return the verification point IDTestPage_IDTestPage object in the SUT.
	 */
	protected IFtVerificationPoint IDTestPage_IDTestPageVP() 
	{
		return vp("IDTestPage_IDTestPage");
	}
	protected IFtVerificationPoint IDTestPage_IDTestPageVP(TestObject anchor)
	{
		return vp("IDTestPage_IDTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point LinkTestPage_LinkTestPage object in the SUT.
	 */
	protected IFtVerificationPoint LinkTestPage_LinkTestPageVP() 
	{
		return vp("LinkTestPage_LinkTestPage");
	}
	protected IFtVerificationPoint LinkTestPage_LinkTestPageVP(TestObject anchor)
	{
		return vp("LinkTestPage_LinkTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point LinkTestPage_LinkTestPage_2 object in the SUT.
	 */
	protected IFtVerificationPoint LinkTestPage_LinkTestPage_2VP() 
	{
		return vp("LinkTestPage_LinkTestPage_2");
	}
	protected IFtVerificationPoint LinkTestPage_LinkTestPage_2VP(TestObject anchor)
	{
		return vp("LinkTestPage_LinkTestPage_2", anchor);
	}
	
	/**
	 * Locate and return the verification point LongLinkTestPage_LongLinkTestPage object in the SUT.
	 */
	protected IFtVerificationPoint LongLinkTestPage_LongLinkTestPageVP() 
	{
		return vp("LongLinkTestPage_LongLinkTestPage");
	}
	protected IFtVerificationPoint LongLinkTestPage_LongLinkTestPageVP(TestObject anchor)
	{
		return vp("LongLinkTestPage_LongLinkTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point LongLinkTestTHisIsTheLongLinkT_text object in the SUT.
	 */
	protected IFtVerificationPoint LongLinkTestTHisIsTheLongLinkT_textVP() 
	{
		return vp("LongLinkTestTHisIsTheLongLinkT_text");
	}
	protected IFtVerificationPoint LongLinkTestTHisIsTheLongLinkT_textVP(TestObject anchor)
	{
		return vp("LongLinkTestTHisIsTheLongLinkT_text", anchor);
	}
	
	/**
	 * Locate and return the verification point LongLinkTestTHisIsTheLongLinkT_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint LongLinkTestTHisIsTheLongLinkT_text_2VP() 
	{
		return vp("LongLinkTestTHisIsTheLongLinkT_text_2");
	}
	protected IFtVerificationPoint LongLinkTestTHisIsTheLongLinkT_text_2VP(TestObject anchor)
	{
		return vp("LongLinkTestTHisIsTheLongLinkT_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point NameIDAndAltTextTestPage_NameIDAndAltTextTestPage object in the SUT.
	 */
	protected IFtVerificationPoint NameIDAndAltTextTestPage_NameIDAndAltTextTestPageVP() 
	{
		return vp("NameIDAndAltTextTestPage_NameIDAndAltTextTestPage");
	}
	protected IFtVerificationPoint NameIDAndAltTextTestPage_NameIDAndAltTextTestPageVP(TestObject anchor)
	{
		return vp("NameIDAndAltTextTestPage_NameIDAndAltTextTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point NameIDTestPage_NameIDTestPage object in the SUT.
	 */
	protected IFtVerificationPoint NameIDTestPage_NameIDTestPageVP() 
	{
		return vp("NameIDTestPage_NameIDTestPage");
	}
	protected IFtVerificationPoint NameIDTestPage_NameIDTestPageVP(TestObject anchor)
	{
		return vp("NameIDTestPage_NameIDTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point NameTestPage_NameTestPage object in the SUT.
	 */
	protected IFtVerificationPoint NameTestPage_NameTestPageVP() 
	{
		return vp("NameTestPage_NameTestPage");
	}
	protected IFtVerificationPoint NameTestPage_NameTestPageVP(TestObject anchor)
	{
		return vp("NameTestPage_NameTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point nametest_text object in the SUT.
	 */
	protected IFtVerificationPoint nametest_textVP() 
	{
		return vp("nametest_text");
	}
	protected IFtVerificationPoint nametest_textVP(TestObject anchor)
	{
		return vp("nametest_text", anchor);
	}
	
	/**
	 * Locate and return the verification point NoALTTextTestPage_NoALTTextTestPage object in the SUT.
	 */
	protected IFtVerificationPoint NoALTTextTestPage_NoALTTextTestPageVP() 
	{
		return vp("NoALTTextTestPage_NoALTTextTestPage");
	}
	protected IFtVerificationPoint NoALTTextTestPage_NoALTTextTestPageVP(TestObject anchor)
	{
		return vp("NoALTTextTestPage_NoALTTextTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point offer_offer object in the SUT.
	 */
	protected IFtVerificationPoint offer_offerVP() 
	{
		return vp("offer_offer");
	}
	protected IFtVerificationPoint offer_offerVP(TestObject anchor)
	{
		return vp("offer_offer", anchor);
	}
	
	/**
	 * Locate and return the verification point offer_offer_2 object in the SUT.
	 */
	protected IFtVerificationPoint offer_offer_2VP() 
	{
		return vp("offer_offer_2");
	}
	protected IFtVerificationPoint offer_offer_2VP(TestObject anchor)
	{
		return vp("offer_offer_2", anchor);
	}
	
	/**
	 * Locate and return the verification point regionalGardeningMap_regionalGardeningMap object in the SUT.
	 */
	protected IFtVerificationPoint regionalGardeningMap_regionalGardeningMapVP() 
	{
		return vp("regionalGardeningMap_regionalGardeningMap");
	}
	protected IFtVerificationPoint regionalGardeningMap_regionalGardeningMapVP(TestObject anchor)
	{
		return vp("regionalGardeningMap_regionalGardeningMap", anchor);
	}
	
	/**
	 * Locate and return the verification point TextTaggedAsLinkTest_text object in the SUT.
	 */
	protected IFtVerificationPoint TextTaggedAsLinkTest_textVP() 
	{
		return vp("TextTaggedAsLinkTest_text");
	}
	protected IFtVerificationPoint TextTaggedAsLinkTest_textVP(TestObject anchor)
	{
		return vp("TextTaggedAsLinkTest_text", anchor);
	}
	
	/**
	 * Locate and return the verification point TheOTHERLongLinkTestPage_TheOTHERLongLinkTestPage object in the SUT.
	 */
	protected IFtVerificationPoint TheOTHERLongLinkTestPage_TheOTHERLongLinkTestPageVP() 
	{
		return vp("TheOTHERLongLinkTestPage_TheOTHERLongLinkTestPage");
	}
	protected IFtVerificationPoint TheOTHERLongLinkTestPage_TheOTHERLongLinkTestPageVP(TestObject anchor)
	{
		return vp("TheOTHERLongLinkTestPage_TheOTHERLongLinkTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point ThisIsTheTitleText_text object in the SUT.
	 */
	protected IFtVerificationPoint ThisIsTheTitleText_textVP() 
	{
		return vp("ThisIsTheTitleText_text");
	}
	protected IFtVerificationPoint ThisIsTheTitleText_textVP(TestObject anchor)
	{
		return vp("ThisIsTheTitleText_text", anchor);
	}
	
	/**
	 * Locate and return the verification point TitleTestPage_TitleTestPage object in the SUT.
	 */
	protected IFtVerificationPoint TitleTestPage_TitleTestPageVP() 
	{
		return vp("TitleTestPage_TitleTestPage");
	}
	protected IFtVerificationPoint TitleTestPage_TitleTestPageVP(TestObject anchor)
	{
		return vp("TitleTestPage_TitleTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point WhatSMyCarWorthIsItWorthSellin_text object in the SUT.
	 */
	protected IFtVerificationPoint WhatSMyCarWorthIsItWorthSellin_textVP() 
	{
		return vp("WhatSMyCarWorthIsItWorthSellin_text");
	}
	protected IFtVerificationPoint WhatSMyCarWorthIsItWorthSellin_textVP(TestObject anchor)
	{
		return vp("WhatSMyCarWorthIsItWorthSellin_text", anchor);
	}
	
	/**
	 * Locate and return the verification point _99__99 object in the SUT.
	 */
	protected IFtVerificationPoint _99__99VP() 
	{
		return vp("_99__99");
	}
	protected IFtVerificationPoint _99__99VP(TestObject anchor)
	{
		return vp("_99__99", anchor);
	}
	
	/**
	 * Locate and return the verification point _WhatSMyCarWorth_text object in the SUT.
	 */
	protected IFtVerificationPoint _WhatSMyCarWorth_textVP() 
	{
		return vp("_WhatSMyCarWorth_text");
	}
	protected IFtVerificationPoint _WhatSMyCarWorth_textVP(TestObject anchor)
	{
		return vp("_WhatSMyCarWorth_text", anchor);
	}
	
	

	protected html_8604_Frames5Helper()
	{
		setScriptName("html_8604_Frames5");
	}
	
}

