// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>html_8604_NestedFrames</b><br>
 * Generated     : <b>2019/02/12 1:00:19 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  February 12, 2019
 * @author JaspreetSinghC
 */
public abstract class html_8604_NestedFramesHelper extends RationalTestScript
{
	/**
	 * Application: with default state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"));
	}
	/**
	 * Application: with specific test context and state.
	 *		.text : Application
	 * 		.class : .Menubar
	 * 		.name : Application
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject applicationmenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("applicationmenuBar"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Reset: with default state.
	 *		.id : 
	 * 		.type : reset
	 * 		.value : Reset
	 * 		.title : 
	 * 		.class : Html.INPUT.reset
	 * 		.name : Reset
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_reset() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reset"));
	}
	/**
	 * Reset: with specific test context and state.
	 *		.id : 
	 * 		.type : reset
	 * 		.value : Reset
	 * 		.title : 
	 * 		.class : Html.INPUT.reset
	 * 		.name : Reset
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_reset(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reset"), anchor, flags);
	}
	
	/**
	 * Submit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"));
	}
	/**
	 * Submit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"), anchor, flags);
	}
	
	/**
	 * YesIWantToRegisterToWinTheComputerChairsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Yes, I want to register to win the computer chair
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesIWantToRegisterToWin() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesIWantToRegisterToWin"));
	}
	/**
	 * YesIWantToRegisterToWinTheComputerChairsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Yes, I want to register to win the computer chair
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : submit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesIWantToRegisterToWin(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesIWantToRegisterToWin"), anchor, flags);
	}
	
	/**
	 * vehicleBike1: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : Bike1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : vehicle
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_vehicleBike1() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_vehicleBike1"));
	}
	/**
	 * vehicleBike1: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : Bike1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : vehicle
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_vehicleBike1(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_vehicleBike1"), anchor, flags);
	}
	
	/**
	 * vehicleCar1: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : Car1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : vehicle
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject checkBox_vehicleCar1() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_vehicleCar1"));
	}
	/**
	 * vehicleCar1: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : Car1
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : vehicle
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject checkBox_vehicleCar1(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_vehicleCar1"), anchor, flags);
	}
	
	/**
	 * ChromeLegacyWindow: with default state.
	 *		.text : Chrome Legacy Window
	 * 		.class : Chrome_RenderWidgetHostHWND
	 * 		.name : Chrome Legacy Window
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject chromeLegacyWindowwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("chromeLegacyWindowwindow"));
	}
	/**
	 * ChromeLegacyWindow: with specific test context and state.
	 *		.text : Chrome Legacy Window
	 * 		.class : Chrome_RenderWidgetHostHWND
	 * 		.name : Chrome Legacy Window
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject chromeLegacyWindowwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("chromeLegacyWindowwindow"), anchor, flags);
	}
	
	/**
	 * ChromeLegacyWindow: with default state.
	 *		.text : null
	 * 		.class : Chrome_RenderWidgetHostHWND
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject chromeLegacyWindowwindow2() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("chromeLegacyWindowwindow2"));
	}
	/**
	 * ChromeLegacyWindow: with specific test context and state.
	 *		.text : null
	 * 		.class : Chrome_RenderWidgetHostHWND
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject chromeLegacyWindowwindow2(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("chromeLegacyWindowwindow2"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel :     
	 * 		accessibleContext.accessibleName : Close
	 * 		.classIndex : 2
	 */
	protected GuiTestObject close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel :     
	 * 		accessibleContext.accessibleName : Close
	 * 		.classIndex : 2
	 */
	protected GuiTestObject close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("close"), anchor, flags);
	}
	
	/**
	 * _404NotFound: with default state.
	 *		.title : 404 Not Found
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/html_form_action.asp?userna ...
	 */
	protected DocumentTestObject document__404NotFound() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document__404NotFound"));
	}
	/**
	 * _404NotFound: with specific test context and state.
	 *		.title : 404 Not Found
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/html_form_action.asp?userna ...
	 */
	protected DocumentTestObject document__404NotFound(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document__404NotFound"), anchor, flags);
	}
	
	/**
	 * AriesWebContestPageIframe: with default state.
	 *		.title : Aries-web contest page - Iframe
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/aries-webContestPageiframe. ...
	 */
	protected DocumentTestObject document_ariesWebContestPageIf() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ariesWebContestPageIf"));
	}
	/**
	 * AriesWebContestPageIframe: with specific test context and state.
	 *		.title : Aries-web contest page - Iframe
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/aries-webContestPageiframe. ...
	 */
	protected DocumentTestObject document_ariesWebContestPageIf(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ariesWebContestPageIf"), anchor, flags);
	}
	
	/**
	 * ContestPage: with default state.
	 *		.title : Contest page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"));
	}
	/**
	 * ContestPage: with specific test context and state.
	 *		.title : Contest page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/visionofficeproducts/conte ...
	 */
	protected DocumentTestObject document_contestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_contestPage"), anchor, flags);
	}
	
	/**
	 * fffGoogleSearch: with default state.
	 *		.title : fff - Google Search
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.google.com/search?source=hp&ei=GxpYXNWLFo-v9QPKx5mIDw&q=fff&oq=fff&g ...
	 */
	protected DocumentTestObject document_fffGoogleSearch() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_fffGoogleSearch"));
	}
	/**
	 * fffGoogleSearch: with specific test context and state.
	 *		.title : fff - Google Search
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.google.com/search?source=hp&ei=GxpYXNWLFo-v9QPKx5mIDw&q=fff&oq=fff&g ...
	 */
	protected DocumentTestObject document_fffGoogleSearch(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_fffGoogleSearch"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebIframeAriesWebCo: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/Aries-webContestPageNestedI ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebIframeAriesWebCo: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/iframe/Aries-webContestPageNestedI ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"), anchor, flags);
	}
	
	/**
	 * _IHaveABikeIHaveACar: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form__IHaveABikeIHaveACar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form__IHaveABikeIHaveACar"));
	}
	/**
	 * _IHaveABikeIHaveACar: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form__IHaveABikeIHaveACar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form__IHaveABikeIHaveACar"), anchor, flags);
	}
	
	/**
	 * f: with default state.
	 *		.id : tsf
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : f
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_f() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_f"));
	}
	/**
	 * f: with specific test context and state.
	 *		.id : tsf
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : f
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_f(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_f"), anchor, flags);
	}
	
	/**
	 * input1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : input1
	 * 		.classIndex : 1
	 */
	protected GuiTestObject form_input1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_input1"));
	}
	/**
	 * input1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : input1
	 * 		.classIndex : 1
	 */
	protected GuiTestObject form_input1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_input1"), anchor, flags);
	}
	
	/**
	 * rso: with default state.
	 *		.id : rso
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_rso() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_rso"));
	}
	/**
	 * rso: with specific test context and state.
	 *		.id : rso
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_rso(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_rso"), anchor, flags);
	}
	
	/**
	 * position: with default state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"));
	}
	/**
	 * position: with specific test context and state.
	 *		.text : Please select from below Professional Staff Management Senior Management Preside ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : position
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_position(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_position"), anchor, flags);
	}
	
	/**
	 * salary: with default state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"));
	}
	/**
	 * salary: with specific test context and state.
	 *		.text : Please select from below Under $25,000 $25,001 to $50,000 $50,001 to $75,000 $75 ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : salary
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_salary(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_salary"), anchor, flags);
	}
	
	/**
	 * MicrosoftWindowsSnipperCaptureForm: with default state.
	 *		.text : null
	 * 		.class : Microsoft-Windows-SnipperCaptureForm
	 * 		.processName : SnippingTool.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject microsoftWindowsSnipperCapture() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("microsoftWindowsSnipperCapture"));
	}
	/**
	 * MicrosoftWindowsSnipperCaptureForm: with specific test context and state.
	 *		.text : null
	 * 		.class : Microsoft-Windows-SnipperCaptureForm
	 * 		.processName : SnippingTool.exe
	 * 		.name : null
	 */
	protected TopLevelSubitemTestObject microsoftWindowsSnipperCapture(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("microsoftWindowsSnipperCapture"), anchor, flags);
	}
	
	/**
	 * MozillaCrashReporter: with default state.
	 *		.text : Mozilla Crash Reporter
	 * 		.class : #32770
	 * 		.processName : crashreporter.exe
	 * 		.name : Mozilla Crash Reporter
	 */
	protected TopLevelSubitemTestObject mozillaCrashReporterwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mozillaCrashReporterwindow"));
	}
	/**
	 * MozillaCrashReporter: with specific test context and state.
	 *		.text : Mozilla Crash Reporter
	 * 		.class : #32770
	 * 		.processName : crashreporter.exe
	 * 		.name : Mozilla Crash Reporter
	 */
	protected TopLevelSubitemTestObject mozillaCrashReporterwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mozillaCrashReporterwindow"), anchor, flags);
	}
	
	/**
	 * NewTabMozillaFirefox: with default state.
	 *		.text : New Tab - Mozilla Firefox
	 * 		.class : MozillaWindowClass
	 * 		.processName : firefox.exe
	 * 		.name : New Tab - Mozilla Firefox
	 */
	protected TopLevelSubitemTestObject newTabMozillaFirefoxwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("newTabMozillaFirefoxwindow"));
	}
	/**
	 * NewTabMozillaFirefox: with specific test context and state.
	 *		.text : New Tab - Mozilla Firefox
	 * 		.class : MozillaWindowClass
	 * 		.processName : firefox.exe
	 * 		.name : New Tab - Mozilla Firefox
	 */
	protected TopLevelSubitemTestObject newTabMozillaFirefoxwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("newTabMozillaFirefoxwindow"), anchor, flags);
	}
	
	/**
	 * NewTab: with default state.
	 *		.class : .Application
	 * 		.name : New Tab
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject newTabwin() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("newTabwin"));
	}
	/**
	 * NewTab: with specific test context and state.
	 *		.class : .Application
	 * 		.name : New Tab
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject newTabwin(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("newTabwin"), anchor, flags);
	}
	
	/**
	 * New: with default state.
	 *		.text : New
	 * 		.class : .Pushbutton
	 * 		.name : New
	 * 		.classIndex : 0
	 */
	protected GuiTestObject newbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("newbutton"));
	}
	/**
	 * New: with specific test context and state.
	 *		.text : New
	 * 		.class : .Pushbutton
	 * 		.name : New
	 * 		.classIndex : 0
	 */
	protected GuiTestObject newbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("newbutton"), anchor, flags);
	}
	
	/**
	 * _404NotFound: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : 404 Not Found
	 */
	protected BrowserTabTestObject pageTab__404NotFound() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab__404NotFound"));
	}
	/**
	 * _404NotFound: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : 404 Not Found
	 */
	protected BrowserTabTestObject pageTab__404NotFound(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab__404NotFound"), anchor, flags);
	}
	
	/**
	 * buyerno: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : no
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : buyer
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_buyerno() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyerno"));
	}
	/**
	 * buyerno: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : no
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : buyer
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_buyerno(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyerno"), anchor, flags);
	}
	
	/**
	 * buyeryes: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : yes
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : buyer
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_buyeryes() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyeryes"));
	}
	/**
	 * buyeryes: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : yes
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : buyer
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_buyeryes(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_buyeryes"), anchor, flags);
	}
	
	/**
	 * SearchOrEnterAddress: with default state.
	 *		.class : .Text
	 * 		.name : Search or enter address
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject searchOrEnterAddresstext() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("searchOrEnterAddresstext"));
	}
	/**
	 * SearchOrEnterAddress: with specific test context and state.
	 *		.class : .Text
	 * 		.name : Search or enter address
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject searchOrEnterAddresstext(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("searchOrEnterAddresstext"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * address: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"));
	}
	/**
	 * address: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : address
	 * 		.classIndex : 1
	 */
	protected TextGuiTestObject text_address(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_address"), anchor, flags);
	}
	
	/**
	 * buyerDescription: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"));
	}
	/**
	 * buyerDescription: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : buyer description
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buyerDescription(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buyerDescription"), anchor, flags);
	}
	
	/**
	 * City: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"));
	}
	/**
	 * City: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : City
	 * 		.classIndex : 2
	 */
	protected TextGuiTestObject text_city(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_city"), anchor, flags);
	}
	
	/**
	 * email: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"));
	}
	/**
	 * email: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : email
	 * 		.classIndex : 5
	 */
	protected TextGuiTestObject text_email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_email"), anchor, flags);
	}
	
	/**
	 * HtmlINPUTText: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"));
	}
	/**
	 * HtmlINPUTText: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_htmlINPUTText(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_htmlINPUTText"), anchor, flags);
	}
	
	/**
	 * Name: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"));
	}
	/**
	 * Name: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name"), anchor, flags);
	}
	
	/**
	 * Name: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 */
	protected TextGuiTestObject text_name2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name2"));
	}
	/**
	 * Name: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name
	 */
	protected TextGuiTestObject text_name2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name2"), anchor, flags);
	}
	
	/**
	 * State: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"));
	}
	/**
	 * State: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : State
	 * 		.classIndex : 3
	 */
	protected TextGuiTestObject text_state(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_state"), anchor, flags);
	}
	
	/**
	 * username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"));
	}
	/**
	 * username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_username"), anchor, flags);
	}
	
	/**
	 * Zip: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"));
	}
	/**
	 * Zip: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Zip
	 * 		.classIndex : 4
	 */
	protected TextGuiTestObject text_zip(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_zip"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point address_text object in the SUT.
	 */
	protected IFtVerificationPoint address_textVP() 
	{
		return vp("address_text");
	}
	protected IFtVerificationPoint address_textVP(TestObject anchor)
	{
		return vp("address_text", anchor);
	}
	
	/**
	 * Locate and return the verification point AriesWebContestPageIframe_AriesWebContestPageIframe object in the SUT.
	 */
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframeVP() 
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe");
	}
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframeVP(TestObject anchor)
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe", anchor);
	}
	
	/**
	 * Locate and return the verification point AriesWebContestPageIframe_AriesWebContestPageIframe_2 object in the SUT.
	 */
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframe_2VP() 
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe_2");
	}
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframe_2VP(TestObject anchor)
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe_2", anchor);
	}
	
	/**
	 * Locate and return the verification point AriesWebContestPageIframe_AriesWebContestPageIframe_3 object in the SUT.
	 */
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframe_3VP() 
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe_3");
	}
	protected IFtVerificationPoint AriesWebContestPageIframe_AriesWebContestPageIframe_3VP(TestObject anchor)
	{
		return vp("AriesWebContestPageIframe_AriesWebContestPageIframe_3", anchor);
	}
	
	/**
	 * Locate and return the verification point buyerDescription_text object in the SUT.
	 */
	protected IFtVerificationPoint buyerDescription_textVP() 
	{
		return vp("buyerDescription_text");
	}
	protected IFtVerificationPoint buyerDescription_textVP(TestObject anchor)
	{
		return vp("buyerDescription_text", anchor);
	}
	
	/**
	 * Locate and return the verification point buyerDescription_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint buyerDescription_text_2VP() 
	{
		return vp("buyerDescription_text_2");
	}
	protected IFtVerificationPoint buyerDescription_text_2VP(TestObject anchor)
	{
		return vp("buyerDescription_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point buyerno_state object in the SUT.
	 */
	protected IFtVerificationPoint buyerno_stateVP() 
	{
		return vp("buyerno_state");
	}
	protected IFtVerificationPoint buyerno_stateVP(TestObject anchor)
	{
		return vp("buyerno_state", anchor);
	}
	
	/**
	 * Locate and return the verification point buyeryes_state object in the SUT.
	 */
	protected IFtVerificationPoint buyeryes_stateVP() 
	{
		return vp("buyeryes_state");
	}
	protected IFtVerificationPoint buyeryes_stateVP(TestObject anchor)
	{
		return vp("buyeryes_state", anchor);
	}
	
	/**
	 * Locate and return the verification point City_text object in the SUT.
	 */
	protected IFtVerificationPoint City_textVP() 
	{
		return vp("City_text");
	}
	protected IFtVerificationPoint City_textVP(TestObject anchor)
	{
		return vp("City_text", anchor);
	}
	
	/**
	 * Locate and return the verification point ContestPage_ContestPage object in the SUT.
	 */
	protected IFtVerificationPoint ContestPage_ContestPageVP() 
	{
		return vp("ContestPage_ContestPage");
	}
	protected IFtVerificationPoint ContestPage_ContestPageVP(TestObject anchor)
	{
		return vp("ContestPage_ContestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point email_text object in the SUT.
	 */
	protected IFtVerificationPoint email_textVP() 
	{
		return vp("email_text");
	}
	protected IFtVerificationPoint email_textVP(TestObject anchor)
	{
		return vp("email_text", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlINPUTText_text object in the SUT.
	 */
	protected IFtVerificationPoint HtmlINPUTText_textVP() 
	{
		return vp("HtmlINPUTText_text");
	}
	protected IFtVerificationPoint HtmlINPUTText_textVP(TestObject anchor)
	{
		return vp("HtmlINPUTText_text", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_contentswithchildren object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP() 
	{
		return vp("HtmlTable_0_contentswithchildren");
	}
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP(TestObject anchor)
	{
		return vp("HtmlTable_0_contentswithchildren", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_contentswithchildren_2 object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_contentswithchildren_2VP() 
	{
		return vp("HtmlTable_0_contentswithchildren_2");
	}
	protected IFtVerificationPoint HtmlTable_0_contentswithchildren_2VP(TestObject anchor)
	{
		return vp("HtmlTable_0_contentswithchildren_2", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_contentswithchildren_3 object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_contentswithchildren_3VP() 
	{
		return vp("HtmlTable_0_contentswithchildren_3");
	}
	protected IFtVerificationPoint HtmlTable_0_contentswithchildren_3VP(TestObject anchor)
	{
		return vp("HtmlTable_0_contentswithchildren_3", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_gridVP() 
	{
		return vp("HtmlTable_0_grid");
	}
	protected IFtVerificationPoint HtmlTable_0_gridVP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_text object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_textVP() 
	{
		return vp("HtmlTable_0_text");
	}
	protected IFtVerificationPoint HtmlTable_0_textVP(TestObject anchor)
	{
		return vp("HtmlTable_0_text", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2", anchor);
	}
	
	/**
	 * Locate and return the verification point input1_text object in the SUT.
	 */
	protected IFtVerificationPoint input1_textVP() 
	{
		return vp("input1_text");
	}
	protected IFtVerificationPoint input1_textVP(TestObject anchor)
	{
		return vp("input1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point Name_text object in the SUT.
	 */
	protected IFtVerificationPoint Name_textVP() 
	{
		return vp("Name_text");
	}
	protected IFtVerificationPoint Name_textVP(TestObject anchor)
	{
		return vp("Name_text", anchor);
	}
	
	/**
	 * Locate and return the verification point Name_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint Name_text_2VP() 
	{
		return vp("Name_text_2");
	}
	protected IFtVerificationPoint Name_text_2VP(TestObject anchor)
	{
		return vp("Name_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point position_list object in the SUT.
	 */
	protected IFtVerificationPoint position_listVP() 
	{
		return vp("position_list");
	}
	protected IFtVerificationPoint position_listVP(TestObject anchor)
	{
		return vp("position_list", anchor);
	}
	
	/**
	 * Locate and return the verification point position_selected object in the SUT.
	 */
	protected IFtVerificationPoint position_selectedVP() 
	{
		return vp("position_selected");
	}
	protected IFtVerificationPoint position_selectedVP(TestObject anchor)
	{
		return vp("position_selected", anchor);
	}
	
	/**
	 * Locate and return the verification point Reset_text object in the SUT.
	 */
	protected IFtVerificationPoint Reset_textVP() 
	{
		return vp("Reset_text");
	}
	protected IFtVerificationPoint Reset_textVP(TestObject anchor)
	{
		return vp("Reset_text", anchor);
	}
	
	/**
	 * Locate and return the verification point salary_list object in the SUT.
	 */
	protected IFtVerificationPoint salary_listVP() 
	{
		return vp("salary_list");
	}
	protected IFtVerificationPoint salary_listVP(TestObject anchor)
	{
		return vp("salary_list", anchor);
	}
	
	/**
	 * Locate and return the verification point salary_selected object in the SUT.
	 */
	protected IFtVerificationPoint salary_selectedVP() 
	{
		return vp("salary_selected");
	}
	protected IFtVerificationPoint salary_selectedVP(TestObject anchor)
	{
		return vp("salary_selected", anchor);
	}
	
	/**
	 * Locate and return the verification point Submit_text object in the SUT.
	 */
	protected IFtVerificationPoint Submit_textVP() 
	{
		return vp("Submit_text");
	}
	protected IFtVerificationPoint Submit_textVP(TestObject anchor)
	{
		return vp("Submit_text", anchor);
	}
	
	/**
	 * Locate and return the verification point TestingRFTTestUserADetails_text object in the SUT.
	 */
	protected IFtVerificationPoint TestingRFTTestUserADetails_textVP() 
	{
		return vp("TestingRFTTestUserADetails_text");
	}
	protected IFtVerificationPoint TestingRFTTestUserADetails_textVP(TestObject anchor)
	{
		return vp("TestingRFTTestUserADetails_text", anchor);
	}
	
	/**
	 * Locate and return the verification point username_text object in the SUT.
	 */
	protected IFtVerificationPoint username_textVP() 
	{
		return vp("username_text");
	}
	protected IFtVerificationPoint username_textVP(TestObject anchor)
	{
		return vp("username_text", anchor);
	}
	
	/**
	 * Locate and return the verification point username_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint username_text_2VP() 
	{
		return vp("username_text_2");
	}
	protected IFtVerificationPoint username_text_2VP(TestObject anchor)
	{
		return vp("username_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point vehicleBike1_state object in the SUT.
	 */
	protected IFtVerificationPoint vehicleBike1_stateVP() 
	{
		return vp("vehicleBike1_state");
	}
	protected IFtVerificationPoint vehicleBike1_stateVP(TestObject anchor)
	{
		return vp("vehicleBike1_state", anchor);
	}
	
	/**
	 * Locate and return the verification point vehicleBike1_state_2 object in the SUT.
	 */
	protected IFtVerificationPoint vehicleBike1_state_2VP() 
	{
		return vp("vehicleBike1_state_2");
	}
	protected IFtVerificationPoint vehicleBike1_state_2VP(TestObject anchor)
	{
		return vp("vehicleBike1_state_2", anchor);
	}
	
	/**
	 * Locate and return the verification point vehicleCar1_state object in the SUT.
	 */
	protected IFtVerificationPoint vehicleCar1_stateVP() 
	{
		return vp("vehicleCar1_state");
	}
	protected IFtVerificationPoint vehicleCar1_stateVP(TestObject anchor)
	{
		return vp("vehicleCar1_state", anchor);
	}
	
	/**
	 * Locate and return the verification point vehicleCar1_state_2 object in the SUT.
	 */
	protected IFtVerificationPoint vehicleCar1_state_2VP() 
	{
		return vp("vehicleCar1_state_2");
	}
	protected IFtVerificationPoint vehicleCar1_state_2VP(TestObject anchor)
	{
		return vp("vehicleCar1_state_2", anchor);
	}
	
	/**
	 * Locate and return the verification point YesIWantToRegisterToWinTheComp_text object in the SUT.
	 */
	protected IFtVerificationPoint YesIWantToRegisterToWinTheComp_textVP() 
	{
		return vp("YesIWantToRegisterToWinTheComp_text");
	}
	protected IFtVerificationPoint YesIWantToRegisterToWinTheComp_textVP(TestObject anchor)
	{
		return vp("YesIWantToRegisterToWinTheComp_text", anchor);
	}
	
	/**
	 * Locate and return the verification point _404NotFound__404NotFound object in the SUT.
	 */
	protected IFtVerificationPoint _404NotFound__404NotFoundVP() 
	{
		return vp("_404NotFound__404NotFound");
	}
	protected IFtVerificationPoint _404NotFound__404NotFoundVP(TestObject anchor)
	{
		return vp("_404NotFound__404NotFound", anchor);
	}
	
	/**
	 * Locate and return the verification point _IHaveABikeIHaveACar_text object in the SUT.
	 */
	protected IFtVerificationPoint _IHaveABikeIHaveACar_textVP() 
	{
		return vp("_IHaveABikeIHaveACar_text");
	}
	protected IFtVerificationPoint _IHaveABikeIHaveACar_textVP(TestObject anchor)
	{
		return vp("_IHaveABikeIHaveACar_text", anchor);
	}
	
	

	protected html_8604_NestedFramesHelper()
	{
		setScriptName("html_8604_NestedFrames");
	}
	
}

