// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>html_8604_NestedFrame2</b><br>
 * Generated     : <b>2019/02/12 1:00:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  February 12, 2019
 * @author JaspreetSinghC
 */
public abstract class html_8604_NestedFrame2Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * framsetNiveau1: with default state.
	 *		.title : framset niveau 1
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_framsetNiveau1() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_framsetNiveau1"));
	}
	/**
	 * framsetNiveau1: with specific test context and state.
	 *		.title : framset niveau 1
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_framsetNiveau1(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_framsetNiveau1"), anchor, flags);
	}
	
	/**
	 * header: with default state.
	 *		.title : header
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_header() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_header"));
	}
	/**
	 * header: with specific test context and state.
	 *		.title : header
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_header(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_header"), anchor, flags);
	}
	
	/**
	 * Left: with default state.
	 *		.title : Left
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_left() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_left"));
	}
	/**
	 * Left: with specific test context and state.
	 *		.title : Left
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_left(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_left"), anchor, flags);
	}
	
	/**
	 * Right: with default state.
	 *		.title : Right
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_right() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_right"));
	}
	/**
	 * Right: with specific test context and state.
	 *		.title : Right
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_right(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_right"), anchor, flags);
	}
	
	/**
	 * Right: with default state.
	 *		.title : Right
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_right2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_right2"));
	}
	/**
	 * Right: with specific test context and state.
	 *		.title : Right
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_right2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_right2"), anchor, flags);
	}
	
	/**
	 * default1: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_default1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_default1"));
	}
	/**
	 * default1: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_default1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_default1"), anchor, flags);
	}
	
	/**
	 * default9: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected StatelessGuiSubitemTestObject image_default9() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_default9"));
	}
	/**
	 * default9: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 8
	 */
	protected StatelessGuiSubitemTestObject image_default9(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_default9"), anchor, flags);
	}
	
	/**
	 * NestedFramesSample1Defect45282: with default state.
	 *		.text : Nested Frames Sample 1- defect 45282
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_nestedFramesSample1Defect() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample1Defect"));
	}
	/**
	 * NestedFramesSample1Defect45282: with specific test context and state.
	 *		.text : Nested Frames Sample 1- defect 45282
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_nestedFramesSample1Defect(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample1Defect"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * Name1: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name1"));
	}
	/**
	 * Name1: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : Name1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_name1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_name1"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point default1_default1 object in the SUT.
	 */
	protected IFtVerificationPoint default1_default1VP() 
	{
		return vp("default1_default1");
	}
	protected IFtVerificationPoint default1_default1VP(TestObject anchor)
	{
		return vp("default1_default1", anchor);
	}
	
	/**
	 * Locate and return the verification point default9_default9 object in the SUT.
	 */
	protected IFtVerificationPoint default9_default9VP() 
	{
		return vp("default9_default9");
	}
	protected IFtVerificationPoint default9_default9VP(TestObject anchor)
	{
		return vp("default9_default9", anchor);
	}
	
	/**
	 * Locate and return the verification point header_header object in the SUT.
	 */
	protected IFtVerificationPoint header_headerVP() 
	{
		return vp("header_header");
	}
	protected IFtVerificationPoint header_headerVP(TestObject anchor)
	{
		return vp("header_header", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_contentswithchildren object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP() 
	{
		return vp("HtmlTable_0_contentswithchildren");
	}
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP(TestObject anchor)
	{
		return vp("HtmlTable_0_contentswithchildren", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_grid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_gridVP() 
	{
		return vp("HtmlTable_0_grid");
	}
	protected IFtVerificationPoint HtmlTable_0_gridVP(TestObject anchor)
	{
		return vp("HtmlTable_0_grid", anchor);
	}
	
	/**
	 * Locate and return the verification point Left_Left object in the SUT.
	 */
	protected IFtVerificationPoint Left_LeftVP() 
	{
		return vp("Left_Left");
	}
	protected IFtVerificationPoint Left_LeftVP(TestObject anchor)
	{
		return vp("Left_Left", anchor);
	}
	
	/**
	 * Locate and return the verification point Right_Right object in the SUT.
	 */
	protected IFtVerificationPoint Right_RightVP() 
	{
		return vp("Right_Right");
	}
	protected IFtVerificationPoint Right_RightVP(TestObject anchor)
	{
		return vp("Right_Right", anchor);
	}
	
	/**
	 * Locate and return the verification point Right_Right_2 object in the SUT.
	 */
	protected IFtVerificationPoint Right_Right_2VP() 
	{
		return vp("Right_Right_2");
	}
	protected IFtVerificationPoint Right_Right_2VP(TestObject anchor)
	{
		return vp("Right_Right_2", anchor);
	}
	
	

	protected html_8604_NestedFrame2Helper()
	{
		setScriptName("html_8604_NestedFrame2");
	}
	
}

