// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>html_8604_NestedFrame3</b><br>
 * Generated     : <b>2019/02/12 1:01:06 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  February 12, 2019
 * @author JaspreetSinghC
 */
public abstract class html_8604_NestedFrame3Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * PanelUIMenuButton: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : PanelUI-menu-button
	 */
	protected GuiTestObject button_panelUIMenuButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_panelUIMenuButton"));
	}
	/**
	 * PanelUIMenuButton: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : PanelUI-menu-button
	 */
	protected GuiTestObject button_panelUIMenuButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_panelUIMenuButton"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH2"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH2"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH3() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH3"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH3(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH3"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH4() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH4"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH4(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH4"), anchor, flags);
	}
	
	/**
	 * OuterFrame: with default state.
	 *		.title : Outer Frame
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_outerFrame() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_outerFrame"));
	}
	/**
	 * OuterFrame: with specific test context and state.
	 *		.title : Outer Frame
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 */
	protected DocumentTestObject document_outerFrame(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_outerFrame"), anchor, flags);
	}
	
	/**
	 * NestedFramesSample2Defect45282: with default state.
	 *		.text : Nested Frames Sample 2- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_nestedFramesSample2Defect() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample2Defect"));
	}
	/**
	 * NestedFramesSample2Defect45282: with specific test context and state.
	 *		.text : Nested Frames Sample 2- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_nestedFramesSample2Defect(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample2Defect"), anchor, flags);
	}
	
	/**
	 * text1: with default state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1"));
	}
	/**
	 * text1: with specific test context and state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1"), anchor, flags);
	}
	
	/**
	 * text1: with default state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_2"));
	}
	/**
	 * text1: with specific test context and state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_2"), anchor, flags);
	}
	
	/**
	 * text1: with default state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_3"));
	}
	/**
	 * text1: with specific test context and state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_3"), anchor, flags);
	}
	
	/**
	 * text1: with default state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_4() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_4"));
	}
	/**
	 * text1: with specific test context and state.
	 *		.id : text1
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : text1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_text1_4(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_text1_4"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_4 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_4VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_4");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_4VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_4", anchor);
	}
	
	/**
	 * Locate and return the verification point text1_text object in the SUT.
	 */
	protected IFtVerificationPoint text1_textVP() 
	{
		return vp("text1_text");
	}
	protected IFtVerificationPoint text1_textVP(TestObject anchor)
	{
		return vp("text1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point text1_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint text1_text_2VP() 
	{
		return vp("text1_text_2");
	}
	protected IFtVerificationPoint text1_text_2VP(TestObject anchor)
	{
		return vp("text1_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point text1_text_3 object in the SUT.
	 */
	protected IFtVerificationPoint text1_text_3VP() 
	{
		return vp("text1_text_3");
	}
	protected IFtVerificationPoint text1_text_3VP(TestObject anchor)
	{
		return vp("text1_text_3", anchor);
	}
	
	/**
	 * Locate and return the verification point text1_text_4 object in the SUT.
	 */
	protected IFtVerificationPoint text1_text_4VP() 
	{
		return vp("text1_text_4");
	}
	protected IFtVerificationPoint text1_text_4VP(TestObject anchor)
	{
		return vp("text1_text_4", anchor);
	}
	
	

	protected html_8604_NestedFrame3Helper()
	{
		setScriptName("html_8604_NestedFrame3");
	}
	
}

