// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>html_8604_NestedFrame1</b><br>
 * Generated     : <b>2019/02/12 1:00:45 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 8.1 x86 6.3 <br>
 * 
 * @since  February 12, 2019
 * @author JaspreetSinghC
 */
public abstract class html_8604_NestedFrame1Helper extends RationalTestScript
{
	/**
	 * Back: with default state.
	 *		.text : Back
	 * 		.class : .Menupopup
	 * 		.name : Back
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject backpopupMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("backpopupMenu"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.text : Back
	 * 		.class : .Menupopup
	 * 		.name : Back
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject backpopupMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("backpopupMenu"), anchor, flags);
	}
	
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Submit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : B1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"));
	}
	/**
	 * Submit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Submit
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : B1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_submit"), anchor, flags);
	}
	
	/**
	 * C1on: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : C1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_c1on() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_c1on"));
	}
	/**
	 * C1on: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : C1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_c1on(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_c1on"), anchor, flags);
	}
	
	/**
	 * C3on: with default state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : C3
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject checkBox_c3on() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_c3on"));
	}
	/**
	 * C3on: with specific test context and state.
	 *		.id : 
	 * 		.type : checkbox
	 * 		.value : on
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : C3
	 * 		.classIndex : 2
	 */
	protected ToggleGUITestObject checkBox_c3on(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_c3on"), anchor, flags);
	}
	
	/**
	 * _404NotFound: with default state.
	 *		.title : 404 Not Found
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document__404NotFound() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document__404NotFound"));
	}
	/**
	 * _404NotFound: with specific test context and state.
	 *		.title : 404 Not Found
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document__404NotFound(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document__404NotFound"), anchor, flags);
	}
	
	/**
	 * HomePage: with default state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage"));
	}
	/**
	 * HomePage: with specific test context and state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage"), anchor, flags);
	}
	
	/**
	 * HomePage: with default state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage2"));
	}
	/**
	 * HomePage: with specific test context and state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage2"), anchor, flags);
	}
	
	/**
	 * HomePage: with default state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage3() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage3"));
	}
	/**
	 * HomePage: with specific test context and state.
	 *		.title : Home Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_homePage3(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_homePage3"), anchor, flags);
	}
	
	/**
	 * HTMLTryIt: with default state.
	 *		.title : HTML TryIt
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_htmlTryIt() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_htmlTryIt"));
	}
	/**
	 * HTMLTryIt: with specific test context and state.
	 *		.title : HTML TryIt
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_htmlTryIt(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_htmlTryIt"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH"), anchor, flags);
	}
	
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH2() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH2"));
	}
	/**
	 * httpCivcez229NonprodHclpnpComAriesWebSamplesNestedfram: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_httpCivcez229NonprodH2(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_httpCivcez229NonprodH2"), anchor, flags);
	}
	
	/**
	 * RegressionTestPage: with default state.
	 *		.title : Regression Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/start.htm
	 */
	protected DocumentTestObject document_regressionTestPage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_regressionTestPage"));
	}
	/**
	 * RegressionTestPage: with specific test context and state.
	 *		.title : Regression Test Page
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/start.htm
	 */
	protected DocumentTestObject document_regressionTestPage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_regressionTestPage"), anchor, flags);
	}
	
	/**
	 * Widgets: with default state.
	 *		.title : Widgets
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_widgets() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_widgets"));
	}
	/**
	 * Widgets: with specific test context and state.
	 *		.title : Widgets
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 */
	protected DocumentTestObject document_widgets(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_widgets"), anchor, flags);
	}
	
	/**
	 * form1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : form1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_form1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_form1"));
	}
	/**
	 * form1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : form1
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_form1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_form1"), anchor, flags);
	}
	
	/**
	 * HtmlDialog: with default state.
	 *		.class : Html.Dialog
	 * 		.caption : Confirm close
	 */
	protected TopLevelTestObject html_htmlDialog() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("html_htmlDialog"));
	}
	/**
	 * HtmlDialog: with specific test context and state.
	 *		.class : Html.Dialog
	 * 		.caption : Confirm close
	 */
	protected TopLevelTestObject html_htmlDialog(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("html_htmlDialog"), anchor, flags);
	}
	
	/**
	 * btn1: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn1"));
	}
	/**
	 * btn1: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn1"), anchor, flags);
	}
	
	/**
	 * btn2: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn2"));
	}
	/**
	 * btn2: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn2"), anchor, flags);
	}
	
	/**
	 * btn3: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn3() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn3"));
	}
	/**
	 * btn3: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn3(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn3"), anchor, flags);
	}
	
	/**
	 * btn4: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn4() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn4"));
	}
	/**
	 * btn4: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_btn4(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_btn4"), anchor, flags);
	}
	
	/**
	 * circles: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_circles() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_circles"));
	}
	/**
	 * circles: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_circles(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_circles"), anchor, flags);
	}
	
	/**
	 * ColorLinks: with default state.
	 *		.alt : Color Links
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_colorLinks() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_colorLinks"));
	}
	/**
	 * ColorLinks: with specific test context and state.
	 *		.alt : Color Links
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_colorLinks(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_colorLinks"), anchor, flags);
	}
	
	/**
	 * slidepic: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_slidepic() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_slidepic"));
	}
	/**
	 * slidepic: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_slidepic(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_slidepic"), anchor, flags);
	}
	
	/**
	 * TextImageLink: with default state.
	 *		.alt : Text & Image Link
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_textImageLink() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_textImageLink"));
	}
	/**
	 * TextImageLink: with specific test context and state.
	 *		.alt : Text & Image Link
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_textImageLink(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_textImageLink"), anchor, flags);
	}
	
	/**
	 * titleGif5000Bytes: with default state.
	 *		.alt : title.gif (5000 bytes)
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject image_titleGif5000Bytes() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_titleGif5000Bytes"));
	}
	/**
	 * titleGif5000Bytes: with specific test context and state.
	 *		.alt : title.gif (5000 bytes)
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject image_titleGif5000Bytes(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_titleGif5000Bytes"), anchor, flags);
	}
	
	/**
	 * welcomeGif4000Bytes: with default state.
	 *		.alt : welcome.gif (4000 bytes)
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_welcomeGif4000Bytes() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_welcomeGif4000Bytes"));
	}
	/**
	 * welcomeGif4000Bytes: with specific test context and state.
	 *		.alt : welcome.gif (4000 bytes)
	 * 		.id : 
	 * 		.src : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_welcomeGif4000Bytes(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_welcomeGif4000Bytes"), anchor, flags);
	}
	
	/**
	 * _ImageTextLink: with default state.
	 *		.text :            Image & Text Link
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__ImageTextLink() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__ImageTextLink"));
	}
	/**
	 * _ImageTextLink: with specific test context and state.
	 *		.text :            Image & Text Link
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__ImageTextLink(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__ImageTextLink"), anchor, flags);
	}
	
	/**
	 * _SlideShow: with default state.
	 *		.text :            Slide Show!
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__SlideShow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__SlideShow"));
	}
	/**
	 * _SlideShow: with specific test context and state.
	 *		.text :            Slide Show!
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link__SlideShow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__SlideShow"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.text : Back
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.text : Back
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_back"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.text : Back
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_back2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_back2"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.text : Back
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_back2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_back2"), anchor, flags);
	}
	
	/**
	 * change: with default state.
	 *		.text : change
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_change() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_change"));
	}
	/**
	 * change: with specific test context and state.
	 *		.text : change
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 3
	 */
	protected GuiTestObject link_change(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_change"), anchor, flags);
	}
	
	/**
	 * link1: with default state.
	 *		.text : Submit
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : link1
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_link1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_link1"));
	}
	/**
	 * link1: with specific test context and state.
	 *		.text : Submit
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : link1
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_link1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_link1"), anchor, flags);
	}
	
	/**
	 * ModifiedTryitDefect40117: with default state.
	 *		.text : Modified Tryit! - defect 40117
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_modifiedTryitDefect40117() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_modifiedTryitDefect40117"));
	}
	/**
	 * ModifiedTryitDefect40117: with specific test context and state.
	 *		.text : Modified Tryit! - defect 40117
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_modifiedTryitDefect40117(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_modifiedTryitDefect40117"), anchor, flags);
	}
	
	/**
	 * NestedFramesSample1Defect45282: with default state.
	 *		.text : Nested Frames Sample 1- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_nestedFramesSample1Defect() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample1Defect"));
	}
	/**
	 * NestedFramesSample1Defect45282: with specific test context and state.
	 *		.text : Nested Frames Sample 1- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_nestedFramesSample1Defect(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample1Defect"), anchor, flags);
	}
	
	/**
	 * NestedFramesSample2Defect45282: with default state.
	 *		.text : Nested Frames Sample 2- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_nestedFramesSample2Defect() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample2Defect"));
	}
	/**
	 * NestedFramesSample2Defect45282: with specific test context and state.
	 *		.text : Nested Frames Sample 2- defect 45282
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/45282-NestedF ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_nestedFramesSample2Defect(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_nestedFramesSample2Defect"), anchor, flags);
	}
	
	/**
	 * SLPBug: with default state.
	 *		.text : SLP Bug
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_slpBug() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_slpBug"));
	}
	/**
	 * SLPBug: with specific test context and state.
	 *		.text : SLP Bug
	 * 		.id : 
	 * 		.href : http://civcez229.nonprod.hclpnp.com/aries-web/samples/nestedframes/40117_modifie ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 4
	 */
	protected GuiTestObject link_slpBug(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_slpBug"), anchor, flags);
	}
	
	/**
	 * D1: with default state.
	 *		.text : Choice Box Item 1 Item 2 Item 3 Item 4
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : D1
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_d1() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_d1"));
	}
	/**
	 * D1: with specific test context and state.
	 *		.text : Choice Box Item 1 Item 2 Item 3 Item 4
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : D1
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_d1(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_d1"), anchor, flags);
	}
	
	/**
	 * MozillaDropShadowWindowClass: with default state.
	 *		.text : Back
	 * 		.class : MozillaDropShadowWindowClass
	 * 		.processName : firefox.exe
	 * 		.name : Back
	 */
	protected TopLevelSubitemTestObject mozillaDropShadowWindowClasswi() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mozillaDropShadowWindowClasswi"));
	}
	/**
	 * MozillaDropShadowWindowClass: with specific test context and state.
	 *		.text : Back
	 * 		.class : MozillaDropShadowWindowClass
	 * 		.processName : firefox.exe
	 * 		.name : Back
	 */
	protected TopLevelSubitemTestObject mozillaDropShadowWindowClasswi(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mozillaDropShadowWindowClasswi"), anchor, flags);
	}
	
	/**
	 * MozillaFirefoxStartPage: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Mozilla Firefox Start Page
	 */
	protected BrowserTabTestObject pageTab_mozillaFirefoxStartPag() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_mozillaFirefoxStartPag"));
	}
	/**
	 * MozillaFirefoxStartPage: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Mozilla Firefox Start Page
	 */
	protected BrowserTabTestObject pageTab_mozillaFirefoxStartPag(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_mozillaFirefoxStartPag"), anchor, flags);
	}
	
	/**
	 * R1V1: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : V1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : R1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_r1V1() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_r1V1"));
	}
	/**
	 * R1V1: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : V1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : R1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_r1V1(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_r1V1"), anchor, flags);
	}
	
	/**
	 * R1V2: with default state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : V2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : R1
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_r1V2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_r1V2"));
	}
	/**
	 * R1V2: with specific test context and state.
	 *		.id : 
	 * 		.type : radio
	 * 		.value : V2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : R1
	 * 		.classIndex : 1
	 */
	protected ToggleGUITestObject radioButton_r1V2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_r1V2"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * S1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : S1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_s1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_s1"));
	}
	/**
	 * S1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : S1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_s1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_s1"), anchor, flags);
	}
	
	/**
	 * T1: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : T1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_t1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_t1"));
	}
	/**
	 * T1: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : T1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_t1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_t1"), anchor, flags);
	}
	
	/**
	 * T1: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : T1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_t1_2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_t1_2"));
	}
	/**
	 * T1: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : T1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_t1_2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_t1_2"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point Back_text object in the SUT.
	 */
	protected IFtVerificationPoint Back_textVP() 
	{
		return vp("Back_text");
	}
	protected IFtVerificationPoint Back_textVP(TestObject anchor)
	{
		return vp("Back_text", anchor);
	}
	
	/**
	 * Locate and return the verification point Back_text_2 object in the SUT.
	 */
	protected IFtVerificationPoint Back_text_2VP() 
	{
		return vp("Back_text_2");
	}
	protected IFtVerificationPoint Back_text_2VP(TestObject anchor)
	{
		return vp("Back_text_2", anchor);
	}
	
	/**
	 * Locate and return the verification point change_text object in the SUT.
	 */
	protected IFtVerificationPoint change_textVP() 
	{
		return vp("change_text");
	}
	protected IFtVerificationPoint change_textVP(TestObject anchor)
	{
		return vp("change_text", anchor);
	}
	
	/**
	 * Locate and return the verification point ColorLinks_ColorLinks object in the SUT.
	 */
	protected IFtVerificationPoint ColorLinks_ColorLinksVP() 
	{
		return vp("ColorLinks_ColorLinks");
	}
	protected IFtVerificationPoint ColorLinks_ColorLinksVP(TestObject anchor)
	{
		return vp("ColorLinks_ColorLinks", anchor);
	}
	
	/**
	 * Locate and return the verification point form1_text object in the SUT.
	 */
	protected IFtVerificationPoint form1_textVP() 
	{
		return vp("form1_text");
	}
	protected IFtVerificationPoint form1_textVP(TestObject anchor)
	{
		return vp("form1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point HomePage_HomePage object in the SUT.
	 */
	protected IFtVerificationPoint HomePage_HomePageVP() 
	{
		return vp("HomePage_HomePage");
	}
	protected IFtVerificationPoint HomePage_HomePageVP(TestObject anchor)
	{
		return vp("HomePage_HomePage", anchor);
	}
	
	/**
	 * Locate and return the verification point HomePage_HomePage_2 object in the SUT.
	 */
	protected IFtVerificationPoint HomePage_HomePage_2VP() 
	{
		return vp("HomePage_HomePage_2");
	}
	protected IFtVerificationPoint HomePage_HomePage_2VP(TestObject anchor)
	{
		return vp("HomePage_HomePage_2", anchor);
	}
	
	/**
	 * Locate and return the verification point HomePage_HomePage_3 object in the SUT.
	 */
	protected IFtVerificationPoint HomePage_HomePage_3VP() 
	{
		return vp("HomePage_HomePage_3");
	}
	protected IFtVerificationPoint HomePage_HomePage_3VP(TestObject anchor)
	{
		return vp("HomePage_HomePage_3", anchor);
	}
	
	/**
	 * Locate and return the verification point HomePage_HomePage_4 object in the SUT.
	 */
	protected IFtVerificationPoint HomePage_HomePage_4VP() 
	{
		return vp("HomePage_HomePage_4");
	}
	protected IFtVerificationPoint HomePage_HomePage_4VP(TestObject anchor)
	{
		return vp("HomePage_HomePage_4", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_contentswithchildren object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP() 
	{
		return vp("HtmlTable_0_contentswithchildren");
	}
	protected IFtVerificationPoint HtmlTable_0_contentswithchildrenVP(TestObject anchor)
	{
		return vp("HtmlTable_0_contentswithchildren", anchor);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_visiblegrid object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_visiblegridVP() 
	{
		return vp("HtmlTable_0_visiblegrid");
	}
	protected IFtVerificationPoint HtmlTable_0_visiblegridVP(TestObject anchor)
	{
		return vp("HtmlTable_0_visiblegrid", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComAVP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_2", anchor);
	}
	
	/**
	 * Locate and return the verification point httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3 object in the SUT.
	 */
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3VP() 
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3");
	}
	protected IFtVerificationPoint httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3VP(TestObject anchor)
	{
		return vp("httpCivcez229NonprodHclpnpComA_httpCivcez229NonprodHclpnpComA_3", anchor);
	}
	
	/**
	 * Locate and return the verification point link1_text object in the SUT.
	 */
	protected IFtVerificationPoint link1_textVP() 
	{
		return vp("link1_text");
	}
	protected IFtVerificationPoint link1_textVP(TestObject anchor)
	{
		return vp("link1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point ModifiedTryitDefect40117_text object in the SUT.
	 */
	protected IFtVerificationPoint ModifiedTryitDefect40117_textVP() 
	{
		return vp("ModifiedTryitDefect40117_text");
	}
	protected IFtVerificationPoint ModifiedTryitDefect40117_textVP(TestObject anchor)
	{
		return vp("ModifiedTryitDefect40117_text", anchor);
	}
	
	/**
	 * Locate and return the verification point NestedFramesSample1Defect45282_text object in the SUT.
	 */
	protected IFtVerificationPoint NestedFramesSample1Defect45282_textVP() 
	{
		return vp("NestedFramesSample1Defect45282_text");
	}
	protected IFtVerificationPoint NestedFramesSample1Defect45282_textVP(TestObject anchor)
	{
		return vp("NestedFramesSample1Defect45282_text", anchor);
	}
	
	/**
	 * Locate and return the verification point NestedFramesSample2Defect45282_text object in the SUT.
	 */
	protected IFtVerificationPoint NestedFramesSample2Defect45282_textVP() 
	{
		return vp("NestedFramesSample2Defect45282_text");
	}
	protected IFtVerificationPoint NestedFramesSample2Defect45282_textVP(TestObject anchor)
	{
		return vp("NestedFramesSample2Defect45282_text", anchor);
	}
	
	/**
	 * Locate and return the verification point RegressionTestPage_RegressionTestPage object in the SUT.
	 */
	protected IFtVerificationPoint RegressionTestPage_RegressionTestPageVP() 
	{
		return vp("RegressionTestPage_RegressionTestPage");
	}
	protected IFtVerificationPoint RegressionTestPage_RegressionTestPageVP(TestObject anchor)
	{
		return vp("RegressionTestPage_RegressionTestPage", anchor);
	}
	
	/**
	 * Locate and return the verification point S1_text object in the SUT.
	 */
	protected IFtVerificationPoint S1_textVP() 
	{
		return vp("S1_text");
	}
	protected IFtVerificationPoint S1_textVP(TestObject anchor)
	{
		return vp("S1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point slidepic_slidepic object in the SUT.
	 */
	protected IFtVerificationPoint slidepic_slidepicVP() 
	{
		return vp("slidepic_slidepic");
	}
	protected IFtVerificationPoint slidepic_slidepicVP(TestObject anchor)
	{
		return vp("slidepic_slidepic", anchor);
	}
	
	/**
	 * Locate and return the verification point SLPBug_text object in the SUT.
	 */
	protected IFtVerificationPoint SLPBug_textVP() 
	{
		return vp("SLPBug_text");
	}
	protected IFtVerificationPoint SLPBug_textVP(TestObject anchor)
	{
		return vp("SLPBug_text", anchor);
	}
	
	/**
	 * Locate and return the verification point T1_text object in the SUT.
	 */
	protected IFtVerificationPoint T1_textVP() 
	{
		return vp("T1_text");
	}
	protected IFtVerificationPoint T1_textVP(TestObject anchor)
	{
		return vp("T1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point TextImageLink_TextImageLink object in the SUT.
	 */
	protected IFtVerificationPoint TextImageLink_TextImageLinkVP() 
	{
		return vp("TextImageLink_TextImageLink");
	}
	protected IFtVerificationPoint TextImageLink_TextImageLinkVP(TestObject anchor)
	{
		return vp("TextImageLink_TextImageLink", anchor);
	}
	
	/**
	 * Locate and return the verification point titleGif5000Bytes_titleGif5000Bytes object in the SUT.
	 */
	protected IFtVerificationPoint titleGif5000Bytes_titleGif5000BytesVP() 
	{
		return vp("titleGif5000Bytes_titleGif5000Bytes");
	}
	protected IFtVerificationPoint titleGif5000Bytes_titleGif5000BytesVP(TestObject anchor)
	{
		return vp("titleGif5000Bytes_titleGif5000Bytes", anchor);
	}
	
	/**
	 * Locate and return the verification point titleGif5000Bytes_titleGif5000Bytes_2 object in the SUT.
	 */
	protected IFtVerificationPoint titleGif5000Bytes_titleGif5000Bytes_2VP() 
	{
		return vp("titleGif5000Bytes_titleGif5000Bytes_2");
	}
	protected IFtVerificationPoint titleGif5000Bytes_titleGif5000Bytes_2VP(TestObject anchor)
	{
		return vp("titleGif5000Bytes_titleGif5000Bytes_2", anchor);
	}
	
	/**
	 * Locate and return the verification point welcomeGif4000Bytes_welcomeGif4000Bytes object in the SUT.
	 */
	protected IFtVerificationPoint welcomeGif4000Bytes_welcomeGif4000BytesVP() 
	{
		return vp("welcomeGif4000Bytes_welcomeGif4000Bytes");
	}
	protected IFtVerificationPoint welcomeGif4000Bytes_welcomeGif4000BytesVP(TestObject anchor)
	{
		return vp("welcomeGif4000Bytes_welcomeGif4000Bytes", anchor);
	}
	
	/**
	 * Locate and return the verification point Widgets_Widgets object in the SUT.
	 */
	protected IFtVerificationPoint Widgets_WidgetsVP() 
	{
		return vp("Widgets_Widgets");
	}
	protected IFtVerificationPoint Widgets_WidgetsVP(TestObject anchor)
	{
		return vp("Widgets_Widgets", anchor);
	}
	
	/**
	 * Locate and return the verification point Widgets_Widgets_2 object in the SUT.
	 */
	protected IFtVerificationPoint Widgets_Widgets_2VP() 
	{
		return vp("Widgets_Widgets_2");
	}
	protected IFtVerificationPoint Widgets_Widgets_2VP(TestObject anchor)
	{
		return vp("Widgets_Widgets_2", anchor);
	}
	
	/**
	 * Locate and return the verification point Widgets_Widgets_3 object in the SUT.
	 */
	protected IFtVerificationPoint Widgets_Widgets_3VP() 
	{
		return vp("Widgets_Widgets_3");
	}
	protected IFtVerificationPoint Widgets_Widgets_3VP(TestObject anchor)
	{
		return vp("Widgets_Widgets_3", anchor);
	}
	
	/**
	 * Locate and return the verification point _404NotFound__404NotFound object in the SUT.
	 */
	protected IFtVerificationPoint _404NotFound__404NotFoundVP() 
	{
		return vp("_404NotFound__404NotFound");
	}
	protected IFtVerificationPoint _404NotFound__404NotFoundVP(TestObject anchor)
	{
		return vp("_404NotFound__404NotFound", anchor);
	}
	
	/**
	 * Locate and return the verification point _ImageTextLink_text object in the SUT.
	 */
	protected IFtVerificationPoint _ImageTextLink_textVP() 
	{
		return vp("_ImageTextLink_text");
	}
	protected IFtVerificationPoint _ImageTextLink_textVP(TestObject anchor)
	{
		return vp("_ImageTextLink_text", anchor);
	}
	
	/**
	 * Locate and return the verification point _SlideShow_text object in the SUT.
	 */
	protected IFtVerificationPoint _SlideShow_textVP() 
	{
		return vp("_SlideShow_text");
	}
	protected IFtVerificationPoint _SlideShow_textVP(TestObject anchor)
	{
		return vp("_SlideShow_text", anchor);
	}
	
	

	protected html_8604_NestedFrame1Helper()
	{
		setScriptName("html_8604_NestedFrame1");
	}
	
}

