// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Native_HTML_FF1</b><br>
 * Generated     : <b>2020/05/29 4:01:17 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  May 29, 2020
 * @author jhansi.m
 */
public abstract class Native_HTML_FF1Helper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * IBMIndia: with default state.
	 *		.title : IBM - India
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/in-en
	 */
	protected DocumentTestObject document_ibmIndia() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmIndia"));
	}
	/**
	 * IBMIndia: with specific test context and state.
	 *		.title : IBM - India
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/in-en
	 */
	protected DocumentTestObject document_ibmIndia(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmIndia"), anchor, flags);
	}
	
	/**
	 * IBMSearch: with default state.
	 *		.title : IBM Search
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/search?lang=en&cc=in&q=test1
	 */
	protected DocumentTestObject document_ibmSearch() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmSearch"));
	}
	/**
	 * IBMSearch: with specific test context and state.
	 *		.title : IBM Search
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/search?lang=en&cc=in&q=test1
	 */
	protected DocumentTestObject document_ibmSearch(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmSearch"), anchor, flags);
	}
	
	/**
	 * IBMSupportIndia: with default state.
	 *		.title : IBM Support - India
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/support/in/en/?lnk=msu_inen
	 */
	protected DocumentTestObject document_ibmSupportIndia() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmSupportIndia"));
	}
	/**
	 * IBMSupportIndia: with specific test context and state.
	 *		.title : IBM Support - India
	 * 		.class : Html.HtmlDocument
	 * 		.url : https://www.ibm.com/support/in/en/?lnk=msu_inen
	 */
	protected DocumentTestObject document_ibmSupportIndia(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_ibmSupportIndia"), anchor, flags);
	}
	
	/**
	 * ibmLeadspaceBody: with default state.
	 *		.id : ibm-leadspace-body
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_ibmLeadspaceBody() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ibmLeadspaceBody"));
	}
	/**
	 * ibmLeadspaceBody: with specific test context and state.
	 *		.id : ibm-leadspace-body
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_ibmLeadspaceBody(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ibmLeadspaceBody"), anchor, flags);
	}
	
	/**
	 * HtmlA: with default state.
	 *		.text : 
	 * 		.id : 
	 * 		.href : https://www.ibm.com/
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_htmlA() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_htmlA"));
	}
	/**
	 * HtmlA: with specific test context and state.
	 *		.text : 
	 * 		.id : 
	 * 		.href : https://www.ibm.com/
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_htmlA(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_htmlA"), anchor, flags);
	}
	
	/**
	 * IBM: with default state.
	 *		.text : IBM®
	 * 		.href : https://www.ibm.com/in/en?lnk=m
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_ibm() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ibm"));
	}
	/**
	 * IBM: with specific test context and state.
	 *		.text : IBM®
	 * 		.href : https://www.ibm.com/in/en?lnk=m
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_ibm(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_ibm"), anchor, flags);
	}
	
	/**
	 * mhitemMms0: with default state.
	 *		.text : Products
	 * 		.id : mhitem-mms0
	 * 		.href : https://www.ibm.com/in-en
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_mhitemMms0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms0"));
	}
	/**
	 * mhitemMms0: with specific test context and state.
	 *		.text : Products
	 * 		.id : mhitem-mms0
	 * 		.href : https://www.ibm.com/in-en
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_mhitemMms0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms0"), anchor, flags);
	}
	
	/**
	 * mhitemMms1: with default state.
	 *		.text : Services
	 * 		.href : https://www.ibm.com/in-en
	 * 		.id : mhitem-mms1
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_mhitemMms1() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms1"));
	}
	/**
	 * mhitemMms1: with specific test context and state.
	 *		.text : Services
	 * 		.href : https://www.ibm.com/in-en
	 * 		.id : mhitem-mms1
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_mhitemMms1(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms1"), anchor, flags);
	}
	
	/**
	 * mhitemMms2: with default state.
	 *		.text : Industries
	 * 		.href : https://www.ibm.com/in-en/industries?lnk=min
	 * 		.id : mhitem-mms2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_mhitemMms2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms2"));
	}
	/**
	 * mhitemMms2: with specific test context and state.
	 *		.text : Industries
	 * 		.href : https://www.ibm.com/in-en/industries?lnk=min
	 * 		.id : mhitem-mms2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_mhitemMms2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms2"), anchor, flags);
	}
	
	/**
	 * mhitemMms4: with default state.
	 *		.text : Support
	 * 		.id : mhitem-mms4
	 * 		.href : https://www.ibm.com/support/in/en/?lnk=msu_inen
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link_mhitemMms4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms4"));
	}
	/**
	 * mhitemMms4: with specific test context and state.
	 *		.text : Support
	 * 		.id : mhitem-mms4
	 * 		.href : https://www.ibm.com/support/in/en/?lnk=msu_inen
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 7
	 */
	protected GuiTestObject link_mhitemMms4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mhitemMms4"), anchor, flags);
	}
	
	/**
	 * q: with default state.
	 *		.id : q
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_q() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_q"));
	}
	/**
	 * q: with specific test context and state.
	 *		.id : q
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : q
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_q(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_q"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point ibmLeadspaceBody_text object in the SUT.
	 */
	protected IFtVerificationPoint ibmLeadspaceBody_textVP() 
	{
		return vp("ibmLeadspaceBody_text");
	}
	protected IFtVerificationPoint ibmLeadspaceBody_textVP(TestObject anchor)
	{
		return vp("ibmLeadspaceBody_text", anchor);
	}
	
	/**
	 * Locate and return the verification point mhitemMms0_text object in the SUT.
	 */
	protected IFtVerificationPoint mhitemMms0_textVP() 
	{
		return vp("mhitemMms0_text");
	}
	protected IFtVerificationPoint mhitemMms0_textVP(TestObject anchor)
	{
		return vp("mhitemMms0_text", anchor);
	}
	
	/**
	 * Locate and return the verification point mhitemMms1_text object in the SUT.
	 */
	protected IFtVerificationPoint mhitemMms1_textVP() 
	{
		return vp("mhitemMms1_text");
	}
	protected IFtVerificationPoint mhitemMms1_textVP(TestObject anchor)
	{
		return vp("mhitemMms1_text", anchor);
	}
	
	/**
	 * Locate and return the verification point mhitemMms2_text object in the SUT.
	 */
	protected IFtVerificationPoint mhitemMms2_textVP() 
	{
		return vp("mhitemMms2_text");
	}
	protected IFtVerificationPoint mhitemMms2_textVP(TestObject anchor)
	{
		return vp("mhitemMms2_text", anchor);
	}
	
	/**
	 * Locate and return the verification point mhitemMms4_text object in the SUT.
	 */
	protected IFtVerificationPoint mhitemMms4_textVP() 
	{
		return vp("mhitemMms4_text");
	}
	protected IFtVerificationPoint mhitemMms4_textVP(TestObject anchor)
	{
		return vp("mhitemMms4_text", anchor);
	}
	
	

	protected Native_HTML_FF1Helper()
	{
		setScriptName("Native_HTML_FF1");
	}
	
}

